### PR TITLE
Fix #251 #246

### LINKED ISSUE #251: browser test fail
When I run "vhid_send_key_enter" test, som errors ocurred.

webpage oped successfully but, type actions it not working. 

```bash
cscript app.js testloader vhid_send_key_enter data/test-oss-korea-2023.json  
```

first of all.. fix ommited Closing parenthesis

testloader.js
```javascript
    "backup_vmware_esxi": function() {
        var OVFTool = require("lib/ovftool");
        ......

        // do backup
        targetVMs.forEach(function(resourceName) {
            var job = OVFTool.create();
            job.setHostName("example.org");
            job.setResourceName(resourceName);
            job.saveTo("D:\\");
        });  <=== here
```

### Cannot find "AutoItX3.Control" Object.

first one is Cannot find "AutoItX3.Control" Object.

```
[*] error: "AutoItX3.Control" 개체를 생성할 수 없습니다
```

I intall Autoit3 latest version. but It's not working.

app.js
```javascript
    CreateObject.make = function(p, s) {
        if (typeof WScript !== "undefined") {
            if ("CreateObject" in WScript) {
                return WScript.CreateObject(p, s);
            } else {
```

autoit.js
```javascript
function AutoItObject() {
    this._interface = null;

    this.create = function() {
        try {
            this._interface = CreateObject("AutoItX3.Control");
        } catch (e) {
            console.error("AutoIt_CreateObject() ->", e.message);
        }
    };
```

but I think, It's not necessarry . because ChromeObject has autoit Objects...

```javascript
var ChromeObject = function() {
    this.create = function() {
        this.oAutoIt = AutoIt.create();
        this.baseScreenX = 1;
        this.baseScreenY = (!this.isAppMode ? 84 : 32);
        return this;
    };
```

### no debuggint text, no pageList and  ChromeObject.getEvaluatedValue() error

second one is various error..

looks like tests try to get current page list. 
```javascript
[*] ShellObject.exec() -> %comspec% /c (bin\x64\curl-8.12.1_4-win64-mingw\bin\curl.exe -L -X GET -H "User-Agent: php-httpproxy/0.1.5 (Client; WelsonJS; abuse@catswords.net)" -H "Content-Type: application/x-www-form-urlencoded" -A "php-httpproxy/0.1.5 (Client; WelsonJS; abuse@catswords.net)" http://127.0.0.1:9222/json) 1> data\.pipe_8cb8db06 2> data\.pipe_129c67e4
```

but, received 0 bytes.
```
[*] Received 0 bytes
[*] No debugging text
```

But it's passed `isJSONRessponse()`, so errors ocurred..
```javascript
var HTTPObject = function(engine) {
......
        try {
            if (this.engine == "MSXML") {
            ......
            if (this.isJSONResponse()) {
```
fix....

```javascript
            if (responseText && this.isJSONResponse()) {
```

this time, no pageList

```javascript
var ChromeObject = function() {
    ......
    this.getPageList = function() {
        var pageList = [];

        if (this.debuggingPort > 0) {
            try {
                //var responseText = HTTP.get("http://127.0.0.1:" + this.debuggingPort + "/json");
                //console.log(responseText);
                //pageList = JSON.parse(responseText);

                var pageList = HTTP.create("CURL")
                    .setDataType("json")
                    .open("GET", "http://127.0.0.1:" + this.debuggingPort + "/json")
                    .send()
                    .responseBody
                ;

```

finally below errors occured.

` error: ChromeObject.getEvaluatedValue() -> 'JSON.parse(...).result'은(는) null 이거나 개체가 아닙니다.`

### PR DESCRIPTION
**Pull request by gnh1201**
Fix #251 #246

## Summary by Sourcery

Update ChromeObject to use publisherName, streamline path and command handling, improve session and page list operations, and add Whale browser support

New Features:
- Add support for Naver Whale browser in setPublisherName

Bug Fixes:
- Fix default user data directory path to use APPDATA and publisherName
- Correct warning and error messages in session clearing and open methods

Enhancements:
- Rename vendor property to publisherName throughout
- Consolidate userDataDir initialization via setUserDataDir
- Simplify command-line argument quoting and construction in createShoutcut and open methods
- Switch getPageList implementation to use HTTP.get and JSON.parse

Chores:
- Bump version to 0.4.17

## Summary by CodeRabbit

- **New Features**
  - Added support for the "whale" browser.
- **Improvements**
  - Improved naming consistency by updating references from "vendor" to "publisherName".
  - Enhanced default user data directory handling for better compatibility.
  - Refined command line argument formatting for launching browsers.
  - Simplified retrieval of page lists for improved reliability.
- **Other**
  - Updated version information to 0.4.17.

### CODE REVIEW

File: lib/chrome.js [hunk 1]
```diff
@@ -362,7 +313,7 @@ var ChromeObject = function() {
             // release shell
             shell.release();
         } catch (e) {
-            console.error("ChromeObject.open() -> ", e.message);
+            console.error(e.message, ", Error in ChromeObject.open()");
```
Comment (gnh1201) [inline lib/chrome.js]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Log Injection occurs when untrusted user input is directly written to log files without proper sanitization. This can allow attackers to manipulate log entries, potentially leading to security issues like log forging or cross-site scripting. To prevent this, always sanitize user input using `encodeURIComponent()` or `DOMPurify.sanitize()` before logging.  Learn more - https://cwe.mitre.org/data/definitions/117.html

File: lib/chrome.js [hunk 2]
```diff
@@ -91,7 +88,7 @@ var ChromeObject = function() {
             try {
                 return FILE.deleteFolder(FN);
             } catch (e) {
-                console.warn("Can not clear the session! Resaon: " + e.message);
+                console.warn("Can not clear the session! " + e.message);
```
Comment (gnh1201) [inline lib/chrome.js:91]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Log Injection occurs when untrusted user input is directly written to log files without proper sanitization. This can allow attackers to manipulate log entries, potentially leading to security issues like log forging or cross-site scripting. To prevent this, always sanitize user input using `encodeURIComponent()` or `DOMPurify.sanitize()` before logging.  Learn more - https://cwe.mitre.org/data/definitions/117.html
